//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibleDoEpubu.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BibleDoEpubu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;cs&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot;&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///  &lt;link rel=&quot;stylesheet&quot; href=&quot;https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css&quot; integrity=&quot;sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm&quot; crossorigin=&quot;anonymous&quot;&gt;
        ///  &lt;script src=&quot;https://code.jquery.com/jquery-3.2.1.slim.min.js&quot; integrity=&quot;sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN&quot; crossorigi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bible_online_cela {
            get {
                return ResourceManager.GetString("bible_online_cela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;container version=&quot;1.0&quot; xmlns=&quot;urn:oasis:names:tc:opendocument:xmlns:container&quot;&gt;
        ///  &lt;rootfiles&gt;
        ///    &lt;rootfile full-path=&quot;OEBPS/content.opf&quot; media-type=&quot;application/oebps-package+xml&quot; /&gt;
        ///  &lt;/rootfiles&gt;
        ///&lt;/container&gt;.
        /// </summary>
        internal static string container {
            get {
                return ResourceManager.GetString("container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] content {
            get {
                object obj = ResourceManager.GetObject("content", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cover {
            get {
                object obj = ResourceManager.GetObject("cover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot;?&gt;
        ///
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.1//EN&quot; &quot;http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd&quot;&gt;
        ///
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:epub=&quot;http://www.idpf.org/2007/ops&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;{0}&lt;/title&gt;
        ///  &lt;link href=&quot;../css/kniha.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;/&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///{1}
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string kniha {
            get {
                return ResourceManager.GetString("kniha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///  line-height: 1.2;
        ///}
        ///
        ///body * {
        ///  line-height: inherit;
        ///}
        ///
        ///p {
        ///  text-align: justify;
        ///}
        ///
        ///h1, h2 {
        ///  text-align: center;
        ///}
        ///
        ///h3, h4, h5, h6 {
        ///  text-align: left;
        ///}
        ///
        ///sub {
        ///  font-size: 0.675em;
        ///  line-height: 1.2;
        ///  vertical-align: sub;
        ///  vertical-align: -20%;
        ///  color: rgb(150, 150, 150);
        ///}
        ///
        ///sup {
        ///  font-size: 0.675em;
        ///  line-height: 1.2;
        ///  vertical-align: super;
        ///  vertical-align: 35%;
        ///  color: rgb(150, 150, 150);
        ///}
        ///
        ///.poznamka {
        ///  text-decoration: underline;
        ///}
        ///
        ///.kurziva {
        ///  font-style: italic;
        ///}
        ///
        ///.poezi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string kniha_css {
            get {
                return ResourceManager.GetString("kniha_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot;?&gt;
        ///
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.1//EN&quot;
        ///&quot;http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd&quot;&gt;
        ///
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:epub=&quot;http://www.idpf.org/2007/ops&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;{0}&lt;/title&gt;
        ///  &lt;link href=&quot;../css/kniha.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;/&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///&lt;div&gt;
        ///  &lt;img alt=&quot;Obálka&quot; src=&quot;../img/cover.png&quot; style=&quot;height: 100%&quot;/&gt;
        ///&lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string kniha_obalka {
            get {
                return ResourceManager.GetString("kniha_obalka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot;?&gt;
        ///
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.1//EN&quot;
        ///&quot;http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd&quot;&gt;
        ///
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:epub=&quot;http://www.idpf.org/2007/ops&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;Poznámky&lt;/title&gt;
        ///  &lt;link href=&quot;../css/kniha.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;/&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///&lt;h1&gt;Poznámky&lt;/h1&gt;
        ///{0}
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string kniha_poznamky {
            get {
                return ResourceManager.GetString("kniha_poznamky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:epub=&quot;http://www.idpf.org/2007/ops&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;{0}&lt;/title&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;/&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;section epub:type=&quot;frontmatter toc&quot;&gt;
        ///    &lt;header&gt;
        ///      &lt;h1&gt;Obsah&lt;/h1&gt;
        ///    &lt;/header&gt;
        ///    &lt;nav xmlns:epub=&quot;http://www.idpf.org/2007/ops&quot; epub:type=&quot;toc&quot; id=&quot;toc&quot;&gt;
        ///      &lt;ol&gt;
        ///        {1}
        ///      &lt;/ol&gt;
        ///    &lt;/nav&gt;
        ///    &lt;/section&gt;
        ///  &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string kniha_toc {
            get {
                return ResourceManager.GetString("kniha_toc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot;?&gt;
        ///
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.1//EN&quot;
        ///&quot;http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd&quot;&gt;
        ///
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:epub=&quot;http://www.idpf.org/2007/ops&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;{0}&lt;/title&gt;
        ///  &lt;link href=&quot;../css/kniha.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;/&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///&lt;div&gt;
        ///  &lt;img alt=&quot;{0}&quot; src=&quot;../img/logo.png&quot;/&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;p style=&quot;text-align: left;&quot;&gt;
        ///  {0}&lt;br/&gt;&lt;br/&gt;&lt;br/&gt;
        ///  Autor překladu: Alexandr Flek a kol.&lt;br/&gt;
        ///  Vydal: B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string kniha_uvod {
            get {
                return ResourceManager.GetString("kniha_uvod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mimetype {
            get {
                object obj = ResourceManager.GetObject("mimetype", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
