//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibleDoEpubu.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BibleDoEpubu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;container version=&quot;1.0&quot; xmlns=&quot;urn:oasis:names:tc:opendocument:xmlns:container&quot;&gt;
        ///  &lt;rootfiles&gt;
        ///    &lt;rootfile full-path=&quot;OEBPS/content.opf&quot; media-type=&quot;application/oebps-package+xml&quot; /&gt;
        ///  &lt;/rootfiles&gt;
        ///&lt;/container&gt;.
        /// </summary>
        internal static string container {
            get {
                return ResourceManager.GetString("container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] content {
            get {
                object obj = ResourceManager.GetObject("content", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cover {
            get {
                object obj = ResourceManager.GetObject("cover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot;?&gt;
        ///
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.1//EN&quot;
        ///&quot;http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd&quot;&gt;
        ///
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;{0}&lt;/title&gt;
        ///  &lt;link href=&quot;../css/kniha.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;/&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///{1}
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string kniha {
            get {
                return ResourceManager.GetString("kniha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot;?&gt;
        ///
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.1//EN&quot;
        ///&quot;http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd&quot;&gt;
        ///
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;{0}&lt;/title&gt;
        ///  &lt;link href=&quot;../css/kniha.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;/&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///&lt;div&gt;
        ///  &lt;img alt=&quot;Obálka&quot; src=&quot;../img/cover.png&quot; style=&quot;height: 100%&quot;/&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div class=&quot;sgc-1&quot;&gt;
        ///  &lt;img alt=&quot;{0}&quot; src=&quot;../img/logo.png&quot;/&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;p style=&quot;text-align: left;&quot;&gt;
        ///  {0}&lt;br/&gt;&lt;br/&gt;&lt;br/&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string kniha_00_uvod {
            get {
                return ResourceManager.GetString("kniha_00_uvod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p {
        ///  text-align: justify;
        ///}
        ///
        ///.kurziva {
        ///  font-style: italic;
        ///}
        ///
        ///h1, h2 {
        ///  text-align: center;
        ///}
        ///
        ///sup {
        ///  color: gray;
        ///  font-size: xx-small;
        ///}
        ///
        ///.poezie {
        ///  margin-top: 24px;
        ///  margin-bottom: 24px;
        ///  font-style: italic;
        ///  color: rgb(100, 100, 100);
        ///  font-size: small;
        ///}.
        /// </summary>
        internal static string kniha_css {
            get {
                return ResourceManager.GetString("kniha_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot;?&gt;
        ///
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.1//EN&quot;
        ///&quot;http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd&quot;&gt;
        ///
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;Poznámky&lt;/title&gt;
        ///  &lt;link href=&quot;../css/kniha.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;/&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///&lt;h1&gt;Poznámky&lt;/h1&gt;
        ///{0}
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string kniha_XX_poznamky {
            get {
                return ResourceManager.GetString("kniha_XX_poznamky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mimetype {
            get {
                object obj = ResourceManager.GetObject("mimetype", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
